const ArrString = `
hr@edeltaes.com
career@zealousys.com
career@metizsoft.com
jobs@0xblock.co
hrexec2@e2logy.com
devimodi999@gmail.com
shilpa.hr@hupp.tech
career@coretus.com
vinay@honeycombsoftwares.com
hr@resiliencesoft.com
julie.braganza@thegatewaycorp.com
chandni.hr@infoniumtech.com
ripal@theofficeady.com
hr@mart2global.com
hr2s2sotinfotech.com
info@aark.co.in
rashmi.vhits@gmail.com
radhika.majithiya@amenitytech.ai
hr@lanatussystems.com
almighty.developers.1726@gmail.con
hr@proclink.com
shreyanshi@thinktanker.in
career@1lint.com
careers@ditinteractive.com
contact@clementius.com
hr@appicsoftwares.com
bhavana.jai.@talentxo.co
support@talenthirehr.com
hr@developersiq.in
singhindresh400@gmail.com
cpnsolutions.parmeet@gmail.com
anand.gupta@dayhawk.in
hr@braincuber.com
subendra483@gmail.com
info@briotechno.com
hr@adsumoriginator.com
hr@silicosoftware.com
hr@scriptus.in
jobs@daydreamsoft.com
himani@mspireventures.com
contact@infyom.in
amrutha.hirewayconsulting@gmail.com
ujala@hirewayconsulting.in
amee.s4ittech@gmail.com
info@nrninfotech.com
hr@moontechnolabs.com
hr@pxmatrix.com
hr@ansibytecode.com
hr@rlogical.com
hr@payvaltech.com
hr@offbeatsoftwaresolutions.in
team4lease@gmail.com
hr@xceltec.com
hr@concettolabs.com
maninder@designoweb.com
info@freniznsoftwares.com
jshah@raysindia.com
hr@codeclinic.in
careers@growexx.com
hr@dolphinwebsolution.com
hrgreencubes@gmail.com
hr@v3cube.com
hr@excelsiortechnologies.com
shital.talentcorner@gmail.com
hr@maskoid.com
shivani.hrcx@gmail.com
CAREER@CMARIX.COM
solvewins@gmail.com
hr@doubledotts.com
careers@intforcesoftware.com
jobs@excelent.co.in
hr@globalvincitore.com 
kirti.avionic@gmail.com 
piyush.sharma@otuindia.com
hr@youngbrainzinfotech.com
ripalrecruiter@gmail.com
hr@accreteinfo.com
hr@careerinfosystem.com
minakshi.b@communicationcrafts.com
itjobs@instantnaukri.com
ARPITMEHTA_86@REDIFFMAIL.COM
hr@infistack.com
hr@aktivsoftware.com
hroffice@Uptechmind.com
idchumanresources@innsight.com
hr@e-monk.com 
riya@joinyfy.com
hr@apptraitsolutions.com
hr.kbasystems@gmail.com
heena.g@height8tech.com 
bhavna.phulwani@nexuslinkservices.in
cord4.hr@gmail.com
hr@silverwebbuzz.com
hr@vivanshinfotech.com
jobs@regur.net
techeruditehr@gmail.com
vani.cypherox@gmail.com
hr@bytesparkdigital.com
dharmishtha@mayorainfotech.com
vishwa@jobingujarat.com
shitalrm@infusionanalysts.com
info@evoortsolutions.com
hr@xceltec.com
hr@acespritech.com
hr@megamindsunited.com
hr@nstacksoftech.com
hr@excelsiortechnologies.com
hr@xongolab.com
hr@youngbrainzinfotech.com
hr@ultroneous.com
hr@ultroneous.com
info@frenzinsoftwares.com
nivanyarathod@gmail.com
rohit.rao@theonetechnologies.co.in
hr.ravenous@gmail.com 
mittalpanchal0692@gmail.com
jobs.dotpitchtechnologies@gmail.com
career@innopadsolutions.com
pranav.p@vrinsoft.com
shraddha.k@upsquare.in
sourcing07@isparrowservices.com 
career@siliconithub.com
poojan@evincedev.com
devangi@cognitionteam.com
info@advarisk.com
careers@designhenge.com
tom.baker@foxtekrs.com
pjoshi@simplihire.com
hr@coreteams.us
hr@codedrillinfotech.com
priti.chuadhary@lbmsolutions.in
hr@gsptechnologies.com
hrasiaweb@gmail.com
hr@thegirafe.in
hr@webslogin.com
hr@montwebtech.com
di.priyahr@gmail.com
deepak@metafic.co
hr@stelleninfotech.com
career@stelleninfotech.com
veena@maximusindia.co.in
shubha.dixit@technocratshorizons.com
parneet.netweb@gmail.com
hiring@shindezign
neha.bansal@nascenture.com
jasminerathee@zapbuild.com
karuna07chandla@gmail.com
career@stelleninfotech.com
careers@techstriker.com
Navneshsahani@opportunityhubb.com
hr@proponenttechnologies.com
hrhimanshu.netweb@gmail.com
hr@possibilitysolutions.com
hr@frescowebservices.com
hr@codevibez.com
hr@vopratech.com
hr@base2brand.com
hr@whizkraft.net
hr@senselearner.com
hr@glocify.com
hr@netqom.com
hr@vopratech.com
nidhivatsatbi@gmail.com
pooja@Ldttechnology.com
sonia.s@iapptechnologiesllp.com
hr@acewebx.com
hr@mountcode.com
ishita.codebrew@gmail.com
mandeep@webspero.com
priyanka.beatum@gmail.com
simranjit@creedinfotech.com
hr@techosquare.com
mansithestaffers@gmail.com
hr@aicreatives.com
admin@swsofttech.com
Deeksha.Sharma@essitco.com
hr@fourwttechnologies.com
Hr@reboot-software.com
hr@revclerx.com
hr@beyondroot.com
hr@decorosoft.com
minakshi.b@communicationcrafts.com
prachi_waghmare@hcl.com
kmr.nitin23@gmail.com
hr@shivtechnolabs.com
aishwarya.kundu@nlbetch.in
rahuldhiman8847@gmail.com
hello@web30india.com
ayushi.dixit@automationfactory.io
hr@kautilyam.com
divya.m@addresolutions.com
amandeep.kour@mobileprogramming.com
ayaz.tinwala@ascendion.com
taruna.sharma@nlbtech.in
shweta.shahi@manektech.com
kirti.ratnani@acureinformatics.in
saryuthakur.ameotech@gmail.com
hr@offbeatsoftwaresolutions.in
hr@weballures.com 
reetu.saggu@shubpy.com
varsha.p@richestsoft.in
neha@weoinfotech.com
hr@bizdesire.com
hr@erosteps.com
hr@websterztech.com 
hr@oneulsoft.com 
hr@kindlebitglobal.com 
hr@swarnatek.com
hi@ocode.co
bmcloudc2gmail.com 
hr@wp-eventmanager.com
hr@visions.net.in
rimcy@tru.agency
hr@techmind.co.in
hr@swarnatek.com
mehak.bansal@firminiq.com
hr@blivesolutions.com
neepa@rocktechnolabs.com
hr@sivahtech.com
hr@igxact.com
hr@nivara.co
hr@softecerapvtltd.com
hr@softerector.com
gurleen.kaur@weoinfotech.com
dhwani@stelleninfotech.co.uk
kanchan@apex1team.com 
jyotiaggarwal.610weblab@gmail.com
karuna07chandla@gmail.com 
webspiderinfotech.mohali@gmail.com
aarushi.pundir@vinnisoft.org
hr@trustycoders.com
priya@thoughtwin.com
hr@infograins.com
info@ficode.com
cv@aaatechnologies.co.in
we@vauchinfotech.com
hrd@miracleinfotech.com
hr@mypcot.com
info@svpinfotech.com
hr@svpinfotech.com
careers@grayroutes.in
info@stspl.com
hr@masstechbusiness.com
jiten@crescibit.com
hr@fervidia.com
info@cmots.com
contact@kilobytes.in
info@jampottech.com
info@mindclicktechnologies.com
signup@divum.in
hr@developersiq.com
info@developersiq.com
info@xalcontech.com
info@vmvtechsolutions.com
info@hyperlinkinfosystem.com
ask@prodevans.com
help@keev.tech
careers@robosoftin.com
gayatrimudaliar@kanhasoft.com 
jobs@softwareco.com
hr@silverwebbuzz.com
gayatrimudaliar@kanhasoft.com
careers@instalanes.com
susmita@digitalaptech.com
hr@abbacus.com
hr@boffincoders.com
chetan@genesissoftwaretech.com
sales@algoocean.com
support@algoocean.com
hr@acmeminds.com
jobs@techifysolutions.com
minakshi.b@communicationcrafts.com
career@codeflies.com
hr@mcodeinfosoft.com
praniti.bhansali@intesols.com.au
info@hexabrain.com
support@overandalltech.com
merchandise@overandalltech.com
info@webwiztech.com
webwiztech24@gmail.com
sales@mypcot.com
hr@mypcot.com
info@goldenmace.com
hr@goldenmace.com
business@techberryinfotech.com
hello@oneture.com
info@handsintechnology.com
info@konverge.co.in
hr@omega-sys.com
omegasoftmum@gmail.com
info@omega-sys.com
info@wamatechnology.com
info@togglebytes.com
info@qpsit.com
support@celesttechnologies.com
sales@innowrap.com
info@s-ancial.com
careers@s-ancial.com
info@epuratech.com
careers@grayroutes.in
info@acaira.com
enq@spinetechnologies.com 
support@carnot.co.in
primarykeytech@gmail.com
info@seq-lib.org
careers@ascenwork.com
info@e-stonetech.com
sahutechnologies@gmail.com
info@maxus.co.in
india@cahead.com
hr@insteptechnologies.com
sonam@apptunix.com
varsha.p@richestsoft.in
harvinder@suffescom.in
hr@mcsam.in
swati.singh@poulimainfo.tech
shikha.sen@matrixmarketers.com
recruitment@softnotions.com
contact@softnotions.com
careers@revyrieglobal.com
vvijayakumar@4labsinc.com
careers@reflectionsinfos.com
recruit@zoondia.in
jobs@infospica.com
careers@xpetize.com
helly.mehta@codecaste.com
careers@xpetize.com
careers@lifology.com
hrd@way.com
karthika.j@iinerds.com
info@softwebpos.com
careers@grayroutes.in
enq@spinetechnologies.com
primarykeytech@gmail.com
hr@mobilewaretech.com
hr@shadowinfosystem.com
niktia.dhyani@huntingcube.com
info@cantechnologies.co.in
info@codeaspire.in
reachus@binatebits.com
hr@nadcab.com
privacy@raweng.com
gurleen.kaur@weoinfotech.com
sudhanshu@cyberpuzzlenet.com
hr@web1experts.org
info@hashstudioz.com
contacts@unifiedinfotech.net
connect@wittybrains.com
hr@parangat.com
sneha.padve@birlasoft.com
anirban.thakur@birlasoft.com
connectme@newgensoft.com
info@newgensoft.com
info@rnssoft.com
sales@chromeinfotech.com
sales@perfectkode.com
sales@ongraph.com
Info@vedikatpl.com
info@hexadecimalsoftware.com
hr@techwinlabs.com
hr@aicreatives.com
priya.rana@shinedezign.com
info@hsenidbiz.com
info@appther.com
hr@appther.com
hr@appnox.ai
eugene@alchemytech.ca
ramji@simprosys.net
mail@magicedtech.com
dpo@magicedtech.com
hello@liangtuang.com
info@veeersatech.com
info@drabito.com
career@instaceit.com
shilpa.Omninos@gmail.com
amandeep.kaur@capanicus.com
Hr@mindwebtree.com
shubha.dixit@technocratshorizons.com
hr@careerinfosystem.com
rubal@lbmsolutions.in
hr@deepdivemedia.in
hr@submitcore.com
hr@coretechitservices.com
hr@roiminds.com
tripti.29975@lpu.co.in
sjain01ajmer@gmail.com
gurmat.kaur@bridgingtech.com 
manager.hr@cgc.ac.in
tanu.pathania@sdplabs.com
dhwani@stelleninfotech.co.uk
manisha@expandimo.com
sudhanshu@cyberpuzzlenet.com
mandeep@finndit.com 
hr@adaired.com
hr@devherds.com
aanchal.tomar@xicom.biz
vinny@suffescom.co
hr@indicsoft.com
info@indicsoft.com
sales@i-softinc.com
solutions@apptread.com
info@max3logic.com
hr@techwarezen.com
sales@techwarezen.com
info@itcompamyindia.com
manalithakarar@gmail.com
info@chlsoftech.com
hr@a3spl.com
hr@appther.com
info@appther.com
info@a2gsoft.com
info@skysoft.net.in
hr@microberry.in
hr@nstacksoftech.com
hr@sntrix.com
hr2@jeronone.co.in
info@samvidsearch.com
hr.visionvivante@gmail.com
careeritcrossroads@gmail.com
priti.chaudhary@lbmsolutions.in
kalyani@unoiatech.com
kanishka@annulartechnologies.com
hr@zenidinfotech.com
info@artechnolabs.com
hr@knackroot.com
bhoomi@sevensquaretech.com
vishwa.vhits@gmail.com
sunil.m@aarchik.com
hr@sketchish.com
info@exceleurservices.com
hr@linearloop.io
hr@arhamtechnosoft.com
mittal@mobpair.com
helly.innovius@gmail.com
jalpa@thinktanker.in
hello@kreyet.com
buddy@rotonn.com
hr@softrefine.com
shivani@moontechnolabs.com
unnati.pandya@bytestechnolab.com
hrm@proexelancers.com
srikconsulting08@gmail.com
hr@aglowiditsolutions.com
Hiring@competentemporio.com
parul.gupta@dayhawk.in
career@kiraintrilogy.com
manishaaasmo7@gmail.com
khyati.hires@gmail.com
hr@liseinfotech.com
renuka.p@extwebtech.in
Prerna.luthra@antiersolution
varsha.p@richestsoft.in
prafful.walia@digimantra.com
kirthika.m@sensiple.com
jobs@techseria.com
hr@innzes.com
jobs@webtech-evolution.com
hr@matlabinfotech.com
hr@aktivsoftware.com
Info@DeetyaAccountingCodes.com
hr@nimblechapps.com
miteshpandya@moneyphi.com
purvish.pandya@bombaysoftwares.com
parthiv.shah@kmkconsultinginc.com
career@codedrhemes.com
harsh.raval@nexuslinkservices.in
jshetty@sigmasolve.net
hiring@tjcg.in
mahavir.singh@smartdatainc.net
Apurvatiwari@opportunityhubb.com
rinku.ssvtechnologies@gmail.com
venkatasrini2021@gmail.com
hi@ocode.co
hr@smileitsolutions.com
hr@tecxar.io
hr@handstogetehr.tech
jobs@hexotix.com
kinjal.patel@artoonsolutions.com
areer@letmegrab.com
hello@tpots.co
alok@innov8foru.com
hr@sixty13.com
hr@omtecweb.com
hr@codetrinity.com
career@appstonelab.com
careers@kmphitech.com
mehtarushil31@gmail.com
sambashivudu022000@gmail.com
deekshanagar4@gmail.com
hr.codealchemy@gmail.com
Vandana@freebeez.in
hr.loopnix@gmail.com
shital.talentcorner@gmail.com
career@prismitsystems.com
harmeet.kaur@wittybrains.com
hiring@fiftyfivetech.io
gurjeet.kaur@softradix.com
nishita@bitcot.com
sahibhrsolution@gmail.com
careers@7hosty.com
jobs@notioninfosoft.com
careers@radicalloop.com
kamakshi.zigsaw@gmail.com
hr@excelent.co.in
hr.marstechnolabs@gmail.com
hr@ociustechnologies.com
divyani.porwal@trootech.com
Career.shree2021@gmail.com
hiral.solanki@aspiresoftserv.com
hr@aliansoftware.net
dsconsult.india@gmail.com
sandhya.dubey@eliteplacementconsultants.com
manibhadrainfotech1@gmail.com
hr@samptechnologies.com
hr@aim2door.com
career@technocometsolutions.com
hr@clevrs.com
amogh@staffomatix.com
hr@niramisolutions.com
humanssofttech@gmail.com
vani.cypherox@gmail.com
himani@linksture.com
career@worldwebtechnology.com
hr@youngbrainzinfotech.com
hr@doubledotts.com
ankush@pokermagnet.com
adhankhar@voiceoc.com
hr@avioxtechnologies.com
poonam@suffescom.in
hreecodeinfo@gmail.com
hello@lanatussystems.com
hr@smartmoves.co.in
career@evolvan.com
hrwebperfection@gmail.com
hr@trustycoders.com
sangram@senwellsys.com
gaurav.k@kritikalhire.com
hr@freshcodes.in
hr@ebizlab.co
hr@conative.in
sales@heptagonservices.com
info@nugeninfo.com
hr@technoexponent.com
soumitamisra@technoexponent.com
krina.bundela@artoonsolutions.com
info@antixxtechhub.com
hr@nadcab.com
aakash.singh.rana@tarsytech.com
contact@hiringplug.com
jobs@implevisiontech.com
contact@repup.co
career@imprintai.us
hr@keymouseit.com
hr@koltetechsavvy.com
jobs@softwareco.com
mss.kishpinder@gmail.com
asmita@globalvoxinc.com
hr@disolutions.net
hr@grootsoftwares.com
hr@offbeatsoftwaresolutions.in
hr@intellinez.com
hr@joenish.com
hr@zoninnovative.com
jyoti@creativebuffer.com
anmol@novage.ms
asmita@globlvoxinc.com
info@tophatsoft.com
career@quarec.com
hr@xceltec.com
ritika.mehta@mobileprogramming.com
hr@nstacksoftech.com
hr@thesynergyworks.com
hr@nextbraintech.com
mehak.chandigarh@appinventiv.com
zeligzhr@gmail.com
netforth.hr@gmail.com
careers@polynine.com
vaishnavi@thoughtwin.com
abha@theofficeday.com
hr@apptraitsolutions.com
admin@v2infotech.co.in
jobs@zorior.com
hr@hashtechy.com
hr@isyncevolution.com
harsh@imperoit.com
hr@itoneclick.com
hr@v3cube.com
hr@henceforthsolutions.com
archana.d@mucrest.com
jagruti.prajapati@esmsys.com
careers@hops.healthcare 
jobs@solwininfotech.com
hr@letsnurture.com
hr@silverwebbuzz.com
arti@lahagora.in
hr@multiqos.com
hr@webunityinfotech.com
hr@doubledotts.com
hr@lynxsoftech.com
priya@ebizzinfotech.com
info@aark.co.in
hr@quantumitinnovation.com
jobs@naapbooks.in
jobs@techextensor.com
hi@ocode.co
hr@starts360.com
hr@accreteinfo.com
hr@resiliencesoft.com
hr@benzatine.com
hr@xrstudio.in
hr@logbinary.com
jobs@notioninfosoft.com
hr@nettyfy.com
hr@xceltec.com
ripal@theofficeday.com
bhumipatel.bmp@gmail.com
career@appstonelab.com
careers@valcaresystems.com
mansihr6@gmail.com
varsha.prajapati@silvertouch.com
diti.soni@kosytechnolab.com
mehtarushil31@gmail.com
sritama@codez.in
shivani.hrcx@gmal.com
orphosispeople1818@gmail.com
abhi.vrajtechnosys@gmail.com
seerat@formics.io
hr@apolloinfotech.com
harita.j@upsquare.in
vani.cypherox@gmail.com
devi.modi@aipxperts.com
naziya.saiyed@sstechsystem.com
careera@kmphitech.com
hr.weapplinse@gmail.com
jayeshm@systemintegration.in
resume@esmsys.com
info@jobcurator.in
tanvikhandelwal@softgrid.in
labani@kotaielectronics.com
hr@cloudmatetechnologies.com
info@tornet.co
hr@thevritti.com
jobs@mtechzilla.com
girish.nair03@infosys.com
hr@encodedots.com
info@equitysoft.in
hr@technosouls.com
ramesh.prajapati@geniebazaar.com
mail2shwetha.s@gmail.com
kesha.pandya@artoonsolutions.com
hr@silicosoftware.com
hr@ethnicinfotech.com
tulsi@tekpillar.com
hr@samosys.com
hr@cloudsncodes.com
vaishali@takpillar.com
krina.bundela@artoonsolutions.com
deeppikasharma.emaster@gmail.com
recruiter@cqlsys.co.uk
kinjal@artoonsolutions.com
kesha.pandya@artoonsolutions.com
hr@esteplogic.com
Garimajha@opportunityhubb.com
jyotiaggarwal.610weblab@gmail.com
Nasbitha@opportunityhubb.com
abhilasha@mindpathtech.com
crushittechno@gmail.com
hr@shethink.in
rashisharma@luminoguru.com
hr@silicosoftware.com
vrushika@3elixir.com
career@mightquite.com
hr@identixweb.com
info@samvidsearch.com
hr.visionvivante@gmail.com
careeritcrossroads@gmail.com
priti.chaudhary@lbmsolutions.in
kalyani@unoiatech.com
kanishka@annulartechnologies.com
hr@zenidinfotech.com
info@artechnolabs.com
hr@knackroot.com
bhoomi@sevensquaretech.com
vishwa.vhits@gmail.com
sunil.m@aarchik.com
hr@sketchish.com
info@exceleurservices.com
hr@linearloop.io
hr@arhamtechnosoft.com
mittal@mobpair.com
helly.innovius@gmail.com
jalpa@thinktanker.in
hello@kreyet.com
buddy@rotonn.com
hr@softrefine.com
shivani@moontechnolabs.com
unnati.pandya@bytestechnolab.com
hrm@proexelancers.com
srikconsulting08@gmail.com
hr@aglowiditsolutions.com
Hiring@competentemporio.com
parul.gupta@dayhawk.in
career@kiraintrilogy.com
manishaaasmo7@gmail.com
khyati.hires@gmail.com
hr@liseinfotech.com
renuka.p@extwebtech.in
Prerna.luthra@antiersolution
varsha.p@richestsoft.in
prafful.walia@digimantra.com
kirthika.m@sensiple.com
jobs@techseria.com
hr@innzes.com
jobs@webtech-evolution.com
hr@matlabinfotech.com
hr@aktivsoftware.com
Info@DeetyaAccountingCodes.com
hr@nimblechapps.com
miteshpandya@moneyphi.com
purvish.pandya@bombaysoftwares.com
parthiv.shah@kmkconsultinginc.com
career@codedrhemes.com
harsh.raval@nexuslinkservices.in
jshetty@sigmasolve.net
hiring@tjcg.in
mahavir.singh@smartdatainc.net
Apurvatiwari@opportunityhubb.com
rinku.ssvtechnologies@gmail.com
venkatasrini2021@gmail.com
hi@ocode.com
hr@smileitsolutions.com
hr@tecxar.io
hr@handstogetehr.tech
jobs@hexotix.com
kinjal.patel@artoonsolutions.com
areer@letmegrab.com
hello@tpots.co
alok@innov8foru.com
hr@sixty13.com
hr@omtecweb.com
hr@codetrinity.com
career@appstonelab.com
careers@kmphitech.com
mehtarushil31@gmail.com
sambashivudu022000@gmail.com
deekshanagar4@gmail.com
hr.codealchemy@gmail.com
Vandana@freebeez.in
hr.loopnix@gmail.com
shital.talentcorner@gmail.com
career@prismitsystems.com
harmeet.kaur@wittybrains.com
hiring@fiftyfivetech.io
gurjeet.kaur@softradix.com
nishita@bitcot.com
sahibhrsolution@gmail.com
careers@7hosty.com
jobs@notioninfosoft.com
careers@radicalloop.com
kamakshi.zigsaw@gmail.com
hr@excelent.co.in
hr.marstechnolabs@gmail.com
hr@ociustechnologies.com
divyani.porwal@trootech.com
Career.shree2021@gmail.com
hiral.solanki@aspiresoftserv.com
hr@aliansoftware.net
dsconsult.india@gmail.com
sandhya.dubey@eliteplacementconsultants.com
manibhadrainfotech1@gmail.com
hr@samptechnologies.com
hr@aim2door.com
career@technocometsolutions.com
hr@edeltaes.com
career@zealousys.com
career@metizsoft.com
jobs@0xblock.co
hrexec2@e2logy.com
devimodi999@gmail.com
shilpa.hr@hupp.tech
career@coretus.com
vinay@honeycombsoftwares.com
hr@resiliencesoft.com
julie.braganza@thegatewaycorp.com
chandni.hr@infoniumtech.com
ripal@theofficeady.com
hr@mart2global.com
hr2s2sotinfotech.com
info@aark.co.in
rashmi.vhits@gmail.com
radhika.majithiya@amenitytech.ai
hr@lanatussystems.com
almighty.developers.1726@gmail.con
hr@proclink.com
shreyanshi@thinktanker.in
career@1lint.com
careers@ditinteractive.com
contact@clementius.com
hr@appicsoftwares.com
bhavana.jai.@talentxo.co
support@talenthirehr.com
hr@developersiq.in
singhindresh400@gmail.com
cpnsolutions.parmeet@gmail.com
anand.gupta@dayhawk.in
hr@braincuber.com
subendra483@gmail.com
info@briotechno.com
hr@adsumoriginator.com
hr@silicosoftware.com
hr@scriptus.in
jobs@daydreamsoft.com
himani@mspireventures.com
contact@infyom.in
amrutha.hirewayconsulting@gmail.com
ujala@hirewayconsulting.in
amee.s4ittech@gmail.com
info@nrninfotech.com
hr@moontechnolabs.com
hr@pxmatrix.com
hr@ansibytecode.com
hr@rlogical.com
hr@payvaltech.com
hema@brightfutureconsulting.com
hr@offbeatsoftwaresolutions.in
team4lease@gmail.com
hr@xceltec.com
hr@concettolabs.com
maninder@designoweb.com
info@freniznsoftwares.com
jshah@raysindia.com
hr@codeclinic.in
careers@growexx.com
hr@dolphinwebsolution.com
hrgreencubes@gmail.com
hr@v3cube.com
hr@excelsiortechnologies.com
shital.talentcorner@gmail.com
hr@maskoid.com
shivani.hrcx@gmail.com
CAREER@CMARIX.COM
solvewins@gmail.com
hr@doubledotts.com
careers@intforcesoftware.com
jobs@excelent.co.in
hr@globalvincitore.com 
kirti.avionic@gmail.com 
piyush.sharma@otuindia.com
hr@youngbrainzinfotech.com
ripalrecruiter@gmail.com
hr@accreteinfo.com
hr@careerinfosystem.com
minakshi.b@communicationcrafts.com
itjobs@instantnaukri.com
ARPITMEHTA_86@REDIFFMAIL.COM
hr@infistack.com
hr@aktivsoftware.com
hroffice@Uptechmind.com
idchumanresources@innsight.com
hr@e-monk.com 
riya@joinyfy.com
hr@apptraitsolutions.com
hr.kbasystems@gmail.com
heena.g@height8tech.com 
bhavna.phulwani@nexuslinkservices.in
cord4.hr@gmail.com
hr@silverwebbuzz.com
hr@vivanshinfotech.com
jobs@regur.net
techeruditehr@gmail.com
vani.cypherox@gmail.com
hr@bytesparkdigital.com
dharmishtha@mayorainfotech.com
vishwa@jobingujarat.com
shitalrm@infusionanalysts.com
info@evoortsolutions.com
hr@xceltec.com
hr@acespritech.com
hr@megamindsunited.com
hr@nstacksoftech.com
hr@excelsiortechnologies.com
hr@xongolab.com
hr@youngbrainzinfotech.com
hr@ultroneous.com
hr@ultroneous.com
info@frenzinsoftwares.com
nivanyarathod@gmail.com
rohit.rao@theonetechnologies.co.in
hr.ravenous@gmail.com 
mittalpanchal0692@gmail.com
jobs.dotpitchtechnologies@gmail.com
career@innopadsolutions.com
pranav.p@vrinsoft.com
shraddha.k@upsquare.in
sourcing07@isparrowservices.com 
career@siliconithub.com
poojan@evincedev.com
devangi@cognitionteam.com
info@advarisk.com
careers@designhenge.com
tom.baker@foxtekrs.com
pjoshi@simplihire.com
hr@coreteams.us
hr@codedrillinfotech.com
priti.chuadhary@lbmsolutions.in
hr@gsptechnologies.com
hrasiaweb@gmail.com
hr@thegirafe.in
hr@webslogin.com
hr@montwebtech.com
di.priyahr@gmail.com
deepak@metafic.co
hr@stelleninfotech.com
career@stelleninfotech.com
veena@maximusindia.co.in
shubha.dixit@technocratshorizons.com
parneet.netweb@gmail.com
hiring@shindezign
neha.bansal@nascenture.com
jasminerathee@zapbuild.com
karuna07chandla@gmail.com
career@stelleninfotech.com
careers@techstriker.com
Navneshsahani@opportunityhubb.com
hr@proponenttechnologies.com
hrhimanshu.netweb@gmail.com
hr@possibilitysolutions.com
hr@frescowebservices.com
hr@codevibez.com
hr@vopratech.com
hr@base2brand.com
hr@whizkraft.net
hr@senselearner.com
hr@glocify.com
hr@netqom.com
hr@vopratech.com
nidhivatsatbi@gmail.com
pooja@Ldttechnology.com
sonia.s@iapptechnologiesllp.com
hr@acewebx.com
hr@mountcode.com
ishita.codebrew@gmail.com
mandeep@webspero.com
priyanka.beatum@gmail.com
simranjit@creedinfotech.com
hr@techosquare.com
mansithestaffers@gmail.com
hr@aicreatives.com
admin@swsofttech.com
Deeksha.Sharma@essitco.com
hr@fourwttechnologies.com
Hr@reboot-software.com
hr@revclerx.com
hr@beyondroot.com
hr@decorosoft.com
minakshi.b@communicationcrafts.com
prachi_waghmare@hcl.com
kmr.nitin23@gmail.com
hr@shivtechnolabs.com
aishwarya.kundu@nlbetch.in
rahuldhiman8847@gmail.com
hello@web30india.com
ayushi.dixit@automationfactory.io
hr@kautilyam.com
divya.m@addresolutions.com
amandeep.kour@mobileprogramming.com
ayaz.tinwala@ascendion.com
taruna.sharma@nlbtech.in
shweta.shahi@manektech.com
kirti.ratnani@acureinformatics.in
saryuthakur.ameotech@gmail.com
hr@offbeatsoftwaresolutions.in
hr@weballures.com 
reetu.saggu@shubpy.com
varsha.p@richestsoft.in
neha@weoinfotech.com
hr@bizdesire.com
hr@erosteps.com
hr@websterztech.com 
hr@oneulsoft.com 
hr@kindlebitglobal.com 
hr@swarnatek.com
hi@ocode.co
bmcloudc2gmail.com 
hr@wp-eventmanager.com
hr@visions.net.in
rimcy@tru.agency
hr@techmind.co.in
hr@swarnatek.com
mehak.bansal@firminiq.com
hr@blivesolutions.com
neepa@rocktechnolabs.com
hr@sivahtech.com
hr@igxact.com
hr@nivara.co
hr@softecerapvtltd.com
hr@softerector.com
gurleen.kaur@weoinfotech.com
dhwani@stelleninfotech.co.uk
kanchan@apex1team.com 
jyotiaggarwal.610weblab@gmail.com
karuna07chandla@gmail.com 
webspiderinfotech.mohali@gmail.com
aarushi.pundir@vinnisoft.org
hr@trustycoders.com
priya@thoughtwin.com
hr@infograins.com
info@ficode.com
cv@aaatechnologies.co.in
we@vauchinfotech.com
hrd@miracleinfotech.com
hr@mypcot.com
info@svpinfotech.com
hr@svpinfotech.com
careers@grayroutes.in
info@stspl.com
hr@masstechbusiness.com
jiten@crescibit.com
hr@fervidia.com
info@cmots.com
contact@kilobytes.in
info@jampottech.com
info@mindclicktechnologies.com
signup@divum.in
hr@developersiq.com
info@developersiq.com
info@xalcontech.com
info@vmvtechsolutions.com
info@hyperlinkinfosystem.com
ask@prodevans.com
help@keev.tech
careers@robosoftin.com
gayatrimudaliar@kanhasoft.com 
jobs@softwareco.com
hr@silverwebbuzz.com
gayatrimudaliar@kanhasoft.com
careers@instalanes.com
susmita@digitalaptech.com
hr@abbacus.com
hr@boffincoders.com
chetan@genesissoftwaretech.com
sales@algoocean.com
support@algoocean.com
hr@acmeminds.com
jobs@techifysolutions.com
minakshi.b@communicationcrafts.com
career@codeflies.com
hr@mcodeinfosoft.com
praniti.bhansali@intesols.com.au
info@hexabrain.com
support@overandalltech.com
merchandise@overandalltech.com
info@webwiztech.com
webwiztech24@gmail.com
sales@mypcot.com
hr@mypcot.com
info@goldenmace.com
hr@goldenmace.com
business@techberryinfotech.com
hello@oneture.com
info@handsintechnology.com
info@konverge.co.in
hr@omega-sys.com
omegasoftmum@gmail.com
info@omega-sys.com
info@wamatechnology.com
info@togglebytes.com
info@qpsit.com
support@celesttechnologies.com
sales@innowrap.com
info@s-ancial.com
careers@s-ancial.com
info@epuratech.com
careers@grayroutes.in
info@acaira.com
enq@spinetechnologies.com 
support@carnot.co.in
primarykeytech@gmail.com
info@seq-lib.org
careers@ascenwork.com
info@e-stonetech.com
sahutechnologies@gmail.com
info@maxus.co.in
india@cahead.com
hr@insteptechnologies.com
sonam@apptunix.com
varsha.p@richestsoft.in
harvinder@suffescom.in
hr@mcsam.in
swati.singh@poulimainfo.tech
shikha.sen@matrixmarketers.com
recruitment@softnotions.com
contact@softnotions.com
careers@revyrieglobal.com
vvijayakumar@4labsinc.com
careers@reflectionsinfos.com
recruit@zoondia.in
jobs@infospica.com
careers@xpetize.com
helly.mehta@codecaste.com
careers@xpetize.com
careers@lifology.com
hrd@way.com
karthika.j@iinerds.com
info@softwebpos.com
careers@grayroutes.in
enq@spinetechnologies.com
primarykeytech@gmail.com
hr@mobilewaretech.com
hr@shadowinfosystem.com
niktia.dhyani@huntingcube.com
info@cantechnologies.co.in
info@codeaspire.in
reachus@binatebits.com
hr@nadcab.com
privacy@raweng.com
gurleen.kaur@weoinfotech.com
sudhanshu@cyberpuzzlenet.com
hr@web1experts.org
info@hashstudioz.com
contacts@unifiedinfotech.net
connect@wittybrains.com
hr@parangat.com
sneha.padve@birlasoft.com
anirban.thakur@birlasoft.com
connectme@newgensoft.com
info@newgensoft.com
info@rnssoft.com
sales@chromeinfotech.com
sales@perfectkode.com
sales@ongraph.com
Info@vedikatpl.com
info@hexadecimalsoftware.com
hr@techwinlabs.com
hr@aicreatives.com
priya.rana@shinedezign.com
info@hsenidbiz.com
info@appther.com
hr@appther.com
hr@appnox.ai
eugene@alchemytech.ca
ramji@simprosys.net
mail@magicedtech.com
dpo@magicedtech.com
hello@liangtuang.com
info@veeersatech.com
info@drabito.com
career@instaceit.com
shilpa.Omninos@gmail.com
amandeep.kaur@capanicus.com
Hr@mindwebtree.com
shubha.dixit@technocratshorizons.com
hr@careerinfosystem.com
rubal@lbmsolutions.in
hr@deepdivemedia.in
hr@submitcore.com
hr@coretechitservices.com
hr@roiminds.com
tripti.29975@lpu.co.in
sjain01ajmer@gmail.com
gurmat.kaur@bridgingtech.com 
manager.hr@cgc.ac.in
tanu.pathania@sdplabs.com
dhwani@stelleninfotech.co.uk
manisha@expandimo.com
sudhanshu@cyberpuzzlenet.com
mandeep@finndit.com 
hr@adaired.com
hr@devherds.com
aanchal.tomar@xicom.biz
vinny@suffescom.co
hr@indicsoft.com
info@indicsoft.com
sales@i-softinc.com
solutions@apptread.com
info@max3logic.com
hr@techwarezen.com
sales@techwarezen.com
info@itcompamyindia.com
manalithakarar@gmail.com
info@chlsoftech.com
hr@a3spl.com
hr@appther.com
info@appther.com
info@a2gsoft.com
info@skysoft.net.in
hr@microberry.in
hr@nstacksoftech.com
hr@sntrix.com
hr2@jeronone.co.in
`

const st = ArrString.trim().split('\n')


// .......................................................................... Find Unique Mails ./
// // ------------------------------------------------- Date and Time ?
const options = { timeZone: 'Asia/Kolkata' };
const Data_time = new Date().toLocaleString('en-US', options);
// console.log(Date_time);
// ---------------------- .

const fs = require('fs');
const unique = st.filter((item, index) => st.indexOf(item) === index);               // find unique mail
// ------------------------------------ mail seperete one object only 50 mail .
const mail_Count = unique.length // total mails

const groupSize = 50;
const arrMails = [`Total_mail : ${mail_Count}`]

for(let i=0; i < unique.length; i += groupSize){
    const group = unique.slice(i, i + groupSize)

    const mailsObj = {Date_Time:Data_time ,Count:group.length,HrMails:group}
    arrMails.push(mailsObj)
}
// ------------------------------------------------------------------ create file here ./
if(fs.existsSync('./Unique_mail.json')){
    const readFile = fs.readFileSync('./Unique_mail.json','utf-8')
    const readData = JSON.parse(readFile)
    for(let obj of arrMails){
        readData.push(obj)
    }
    fs.writeFileSync('./Unique_mail.json',JSON.stringify(readData,null,4))
    console.log('AllReady created file and store Unique mails...');
}else{
    fs.writeFileSync('./Unique_mail.json',JSON.stringify(arrMails,null,4))
    console.log('CreatNewFile store Unique mails...');
}

// ................................................................................. Find Dublicate Mails ./

const dublicate = st.filter((item, index) => st.indexOf(item) !== index); // find dublicate mail
const mail_Count1 = dublicate.length     // find total mails

// ------------------------------------ mail seperete one object only 50 mail/ [{mail:[50]}] .
const groupSize1 = 50;
const arrMails1 = [`Total_mail : ${mail_Count1}`,`Date_Time:${Data_time}`]

for(let i=0; i < dublicate.length; i += groupSize1){
    const group = dublicate.slice(i, i + groupSize1)

    const mailsObj = {Count:group.length,HrMails:group}
    arrMails1.push(mailsObj)
}
// ------------------------------------------------------------------ create file here ./
if(fs.existsSync('./Dublicate_mail.json')){
    const readFile = fs.readFileSync('./Dublicate_mail.json','utf-8')
    const readData = JSON.parse(readFile)
    for(let obj of arrMails1){
        readData.push(obj)
    }
    fs.writeFileSync('./Dublicate_mail.json',JSON.stringify(readData,null,4))
    console.log('AllReady created file and store Dublicate mails...');
}else{
    fs.writeFileSync('./Dublicate_mail.json',JSON.stringify(arrMails1,null,4))
    console.log('CreatNewFile store Dublicate mails...');
}


// -----------------------------------------------ooooooo

// let uniqueChars = st.filter((item, index) => {
//     return st.indexOf(item) === index;
// });
// // console.log(uniqueChars);

// const fs = require('fs');
// const mailsObj = {HrMails:uniqueChars}
// fs.writeFileSync('data_1.json',JSON.stringify(mailsObj,null,4));
// console.log('Mails Stored Successfully... Remove Dublicate mails...');

// const mailCount = unique.length
// // console.log(mailCount);

// const duplicates = st.filter((item, index) => st.indexOf(item) !== index);
// const mailCount1 = duplicates.length
// const mailsObj1 = {count:mailCount1,HrMails:duplicates}
// fs.writeFileSync('Dublicate_mail.json',JSON.stringify(mailsObj1,null,4));
// console.log('Mails Stored Successfully... Dublicate mails...');